feat: Native HTTP port
fdaciuk/conduit-api pull request #28
Opened 2021-10-19 10:41 UTC by mxthevs

closes #27

2021-11-01 13:18 UTC, mxthevs commented
Hey @fdaciuk,
I think this is good to go, all API tests are passing now.
Maybe we can review this live? It's up to you. I do think that this implementation has space for improvements. 😄

2021-11-01 13:28 UTC, fdaciuk commented
Great idea! Let's review this tomorrow morning at stream! 👯 👯 ✨

2021-11-02 11:24 UTC, fdaciuk requested changes
@mxthevs congrats man, great work!

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/article.ts
> +        slug: request.params![slug] ?? '',
Use `?.` instead of `!`

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/article.ts
> +        slug: request.params![slug] as Slug,
Use `?.` instead of `!`

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/article.ts
> +        slug: request.params![slug] ?? '',
Use `?.` instead of `!`

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/article.ts
> +        slug: request.params![slug] ?? '',
Use `?.` instead of `!`

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/article.ts
> +        slug: request.params![slug] ?? '',
Use `?.` instead of `!`

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/profile.ts
> +        username: request.params![username] ?? '',
Use `?.` instead of `!`

2021-11-02 11:24 UTC, fdaciuk commented on src/ports/native-http/modules/user.ts
> +      (body) => body.user || {},
Use `??` instead of `||`

2021-12-01 10:15 UTC, fdaciuk approved these changes

2021-12-01 10:15 UTC, merged